### ISSUE TITLE
Hmm

### ISSUE THREAD

**Issue by ThisMe124** [Team-IC/mineboty#7]
![IMG_20220106_094617](https://user-images.githubusercontent.com/88891071/148314979-b6f3294b-8fb7-4ebe-b33f-66b9b7e5cc7c.jpg)

**Comment by IndianDevInc** [comment]
You have fill wrong thing in config.json please recheck it
Thank's

**Comment by ThisMe124** [comment]
Ok ;-;

**Comment by ThisMe124** [comment]
Give me config.json full code
