### ISSUE TITLE
Bot doesn't Log in!

### ISSUE THREAD

**Issue by AdvaithVp** [Team-IC/mineboty#9]
I use a login plugin called NLogin. The bot says it has logged in the console *local console where i run the bot, but it gets kicked nd the message said "Took Too LOng to Resgister"

**Comment by abhijith5000** [comment]
how do i make the bot login . even if i tried the bot command of login the bot doesnt login . please help :(

**Comment by Broisp** [comment]
anybody help usss

**Comment by ghost** [comment]
go and watch youtube just seach "Mineboty minecraft replit"

**Comment by IndianDevInc** [comment]
please join our server 
https://team-ic.dev/dc
or
https://discord.gg/VvRDFj2x
